### ISSUE TITLE
IPA is not created for ionic project

### ISSUE THREAD

**Issue by davidmpaz** [bitrise-community/steps-ionic-archive#32]
Hi,

thanks for building support for ionic into Bitrise. I am writing since I am facing some troubles with IPA generation, my guess from logs:
```
Collecting ios outputs
The dsym dir path is now available in the Environment Variable: BITRISE_DSYM_DIR_PATH (value: /Users/vagrant/deploy/distributeWithHockeyApp.app.dSYM)
The dsym.zip path is now available in the Environment Variable: BITRISE_DSYM_PATH (value: /Users/vagrant/deploy/distributeWithHockeyApp.app.dSYM.zip)
The app dir path is now available in the Environment Variable: BITRISE_APP_DIR_PATH (value: /Users/vagrant/deploy/distributeWithHockeyApp.app)
The app.zip path is now available in the Environment Variable: BITRISE_APP_PATH (value: /Users/vagrant/deploy/distributeWithHockeyApp.app.zip)
Collecting android outputs
The apk path is now available in the Environment Variable: BITRISE_APK_PATH (value: /Users/vagrant/deploy/app-release-unsigned.apk)
The apk paths are now available in the Environment Variable: BITRISE_APK_PATH_LIST (value: /Users/vagrant/deploy/app-release-unsigned.apk)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | ionic-archive@1.2.4                                           | 434 sec  |
+---+---------------------------------------------------------------+----------+
```
is that, the step is not generating the file. Do you have any idea on what is happening?

This happens with `ionic-archive@1.2.4`, the project is a test project generated from ionic templates (tutorial template). If you need more information just ask please.

Many thanks in advance,
David

**Comment by BirmacherAkos** [comment]
Hi!

Could you please send your build log?

Just a guess:
Check please that the target is set to `device` in the “Ionic archive” step.
(If it is set to `emulator` it will create a .app for iOS simulator and not for a device. And because of that, the step will not export an IPA.)

**Comment by davidmpaz** [comment]
sorry for the late answer. It was solved already.
The problem was exactly as you sir described

**Comment by ShahriarVelayat** [comment]
I already set the target to `device` but it still doesn't generate ipa output. any solution?

**Comment by bitce** [comment]
Hi @ShahriarVelayat! Please share your build URL with us so we can take a look! We'd prefer if you did this in an issue thread here:https://discuss.bitrise.io/  or on our on-site chat :)
